FROM denoland/deno:latest
ARG VERSION
# ENV DENO_DEPLOYMENT_ID=${VERSION}
ENV PORT=6132

WORKDIR /app

COPY . .
RUN deno cache dev.ts
# RUN deno cache main.ts

EXPOSE 6132

CMD ["run", "-A", "main.ts"]